# Generated by Django 3.1.2 on 2021-04-25 11:25

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import django_xworkflows.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name="Titre de l'article")),
                ('author', models.CharField(db_index=True, max_length=256, verbose_name="Auteur de l'article")),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="corps de l'article")),
                ('status', django_xworkflows.models.StateField(max_length=16, verbose_name='Statut', workflow=django_xworkflows.models._SerializedWorkflow(initial_state='draft', name='PostWorkflow', states=['draft', 'reviewable', 'published', 'deleted']))),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
    ]
