# Generated by Django 4.2.15 on 2025-02-12 10:37

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name="Titre de l'article")),
                ('author', models.CharField(db_index=True, max_length=256, verbose_name="Auteur de l'article")),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="corps de l'article")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('reviewable', 'En revue'), ('published', 'Publié'), ('deleted', 'Supprimé')], default='draft', max_length=256, verbose_name='Statut')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
