# Generated by Django 3.1.2 on 2021-06-12 08:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Nom de la recommandation')),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul.', verbose_name='Slug')),
                ('author', models.CharField(db_index=True, max_length=256, verbose_name='Auteur de la recommandation')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte de la recommandation')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
            },
        ),
    ]
