# Generated by Django 4.2.15 on 2025-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='La description qui sera affichée dans les SERP', max_length=256, verbose_name='Description (balise meta)'),
        ),
        migrations.AddField(
            model_name='competence',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Le titre qui sera affiché dans les SERP', max_length=256, verbose_name='Titre (balise meta)'),
        ),
    ]
